# write aproram to enter 8 numbers and display unique numbers once 

set1=set()
n=int(input("Enter the number: "))
set1.add(n)
n=int(input("Enter the number: "))
set1.add(n)
n=int(input("Enter the number: "))
set1.add(n)
n=int(input("Enter the number: "))
set1.add(n)
n=int(input("Enter the number: "))
set1.add(n)
n=int(input("Enter the number: "))
set1.add(n)
n=int(input("Enter the number: "))
set1.add(n)
n=int(input("Enter the number: "))
set1.add(n)
print(set1)